apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-secrets-operator
  namespace: vault
spec:
  channel: stable
  name: vault-secrets-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: vault-secrets-operator.v0.8.1
  installPlanApproval: Automatic